# Generated by Django 4.1.1 on 2023-06-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0025_alter_externaltransfer_from_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='from_bank',
            field=models.CharField(default='8001', max_length=5),
        ),
    ]
